### ISSUE TITLE
Basic Install Failing

### ISSUE THREAD

**Issue by blackwire** [MycroftAI/padatious#19]
After installing those things needed from the documentation:
`sudo apt-get install libfann-dev python3-dev python3-pip swig`

When I then go to run this:
`pip3 install padatious`

I get this error:
```
Collecting padatious
  Downloading https://files.pythonhosted.org/packages/33/c1/a54ac3f8fe5fac7fc9537beb90576673a660f3da9147e1317adf6e4c3cfb/padatious-0.4.7.tar.gz
Collecting fann2 (from padatious)
  Downloading https://files.pythonhosted.org/packages/80/a1/fed455d25c34a62d4625254880f052502a49461a5dd1b80854387ae2b25f/fann2-1.1.2.tar.gz (66kB)
    100% |████████████████████████████████| 71kB 4.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mui8t_t6/fann2/setup.py", line 92, in <module>
        build_swig()
      File "/tmp/pip-install-mui8t_t6/fann2/setup.py", line 85, in build_swig
        find_fann()
      File "/tmp/pip-install-mui8t_t6/fann2/setup.py", line 73, in find_fann
        raise Exception("Couldn't find FANN source libs!")
    Exception: Couldn't find FANN source libs!
    Looking for FANN libs...

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-mui8t_t6/fann2/
```
This happens on both a WSL (Windows subsystem) and a digital ocean droplet that has the latest version of ubuntu on it. Did the documentation leave something out or did something break?

**Comment by MatthewScholefield** [comment]
I don't remember the situation exactly, but I think this is because the latest version of `libfann-dev` in Ubuntu is out of date. To figure out if this is the issue, can you do one of the following?:
 - `pip3 install fann2==1.0.7` followed by `pip3 install padatious`
 - Try [compiling and installing fann from github](https://github.com/libfann/fann#to-install)

Thanks

**Comment by blackwire** [comment]
I'll give it a go. Thanks!

**Comment by blackwire** [comment]
Worked! Really appreciate that.
