### ISSUE TITLE
Trouble with (|the) in .intent file

### ISSUE THREAD

**Issue by aussieW** [MycroftAI/padatious#3]
Hi

I forked a skill to https://github.com/aussieW/nature-sound-skill which I am trying to improve but I am having an issue with the .intent file under one specific condition.

The .intent file contains:
```
play (|{sound}) relaxation music
listen to {sound} relaxation music
relax (with|to) {sound}
relax to the sound of (|the) {sound}
play (|some) relaxing (music|sounds|{sound})
listen to (|some) relaxing (music|sounds|{sound} 
```
I understand from a recent conversation on Mattermost that the last two lines probably don't work yet.

{sound} represents one of a number of available mp3 files.

The .entity file is dynamically constructed from the available mp3 files. In this case it contains:
```
dawn chorus
rainy river
ocean waves
rainforest
hot spring
urban thunderstorm
tropical storm
```

My problem relates to line 4, 'relax to the sound of (|the) {sound}'. If 'the' is used in any request it always ends up as part of {sound}.

e.g. 'relax to the sound of the rainforest' results in {sound} = 'the rainforest'

**Comment by MatthewScholefield** [comment]
Could you check if this is still an issue? Some of the perfect intent match changes should ensure this is extracted correctly.

**Comment by aussieW** [comment]
Sorry I haven't had time to check this. The skill is till in python2 so needs to be updated to python3 before doing any more testing. I will close for now and reopen if it becomes an issue.

**Comment by penrods** [comment]
Minor note:  The last line is invalid -- it is missing a closing parenthesis for the "(music|..." group.

**Comment by aussieW** [comment]
Checked the actual code on github (link in original post) and it is okay. Must have missed it when I copy pasted the snippet into the message.
