### ISSUE TITLE
Installation - needs python3-fann2 on Ubuntu and Raspberry Pi OS

### ISSUE THREAD

**Issue by lnxusr1** [MycroftAI/padatious#30]
I had a dependency issue in Ubuntu 18.04 and Raspberry Pi OS that required me to also install the FANN bindings.  Recommend updating the Readme to include this dependency.
```
apt-get install python3-fann2
```

**Comment by krisgesling** [comment]
Hey there, is this the same issue as #21?

I just gave it a quick test and after installing this package 20.04 still couldn't find FANN source libs. Was there anything else you did while debugging that might have contributed to the fix?

**Comment by lnxusr1** [comment]
I’m not sure if it is the same issue, but seems to be related.  Basically, the instructions in the readme are just missing the bindings for fann2 for python and this package satisfies that without any hoopla.

**Comment by mbr4477** [comment]
Which version of Python are you using? I think I was able to use `python3-fann2` with Python 3.5 but needed to install FANN2 from source when using Python 3.7.

**Comment by lnxusr1** [comment]
I was using python 3.8 on Ubuntu 20.04.  Will do another fresh install to see if I can more finely pinpoint that though.

**Comment by lnxusr1** [comment]
Indeed, the default on Ubuntu 20.04 is Python 3.8 which requires `python3-fann2` instead of `python3-fann` as the instructions state.  So worth adding a note somewhere that if you're using Ubuntu 20.04 you'll need the other library.

Log attached for reference from a fresh install of Ubuntu 20.04.
[ubuntu20_padatious_install_log.txt](https://github.com/MycroftAI/padatious/files/5070859/ubuntu20_padatious_install_log.txt)

**Comment by lnxusr1** [comment]
I see docs are updated.  thank you.
