### ISSUE TITLE
Inaccurate `intent_file_handler` docs

### ISSUE THREAD

**Issue by ndarilek** [MycroftAI/padatious#6]
From https://mycroft.ai/documentation/padatious/:

The register_intent_file(intent_file, handler) methods arguments are:

    intent_file: the filename of above mentioned intent files without the .intent as argument.

Yet, in my skills:

`@intent_file_handler("stop.info")`

doesn't work, I have to add the _.intent_ extension.

**Comment by MatthewScholefield** [comment]
Thanks for finding this issue with the documentation. I've just update that line so that it now says "with the .intent".
