### ISSUE TITLE
how to load model

### ISSUE THREAD

**Issue by ghost** [MycroftAI/padatious#8]
I am working on it and can't able to load the model. Please help me out for the same.

**Comment by MatthewScholefield** [comment]
What do you mean exactly? What are you trying to do?

**Comment by gagan2103** [comment]
i want to save the train model once in a file and reuse that file to get intents in other script.

**Comment by ghost** [comment]
how to find entity using script.

**Comment by MatthewScholefield** [comment]
What are you using Padatious for? You shouldn't need to deal with loading models since they are auto-generated. All you do is `container.load_entity('foo', 'path/to/foo.entity')`.

**Comment by MatthewScholefield** [comment]
Closing. Feel free to reopen or comment if you have more details.
